### ISSUE TITLE
Getting Error while running on AKS Pods 

### ISSUE THREAD

**Issue by aysahu** [Azure/azure-acr-plugin#28]
Hi,

I am trying to run this plugin on Azure Kubernetes Pods, while it works perfectly fine on master node but it failed on pods with below error 
`Using local directory /home/jenkins/workspace/acr_build_task/. as docker build source.
Compressing local directory into /home/jenkins/workspace/acr_build_task/./a0880edd-d46a-4a22-a9b1-9c2f444241fe.tar.gz.
Compressing ignore rules a0880edd-d46a-4a22-a9b1-9c2f444241fe.tar.gz.
ERROR: No such file or directory
ERROR: ACR Quick Task ended with HasError`

**Comment by yuwzho** [comment]
@aysahu Would you mind showing your pipeline script?

**Comment by yuwzho** [comment]
Thanks for your reporting, I am looking into this one! @aysahu

**Comment by yuwzho** [comment]
Hi @aysahu I have sent out a pull request, would you like to download the [hpi file](https://github.com/yuwzho/azure-acr-plugin/releases/download/0.4.0-snapshot/azure-container-registry-tasks-plugin.hpi) to have a try?

**Comment by aysahu** [comment]
Thanks alot, it is working.
